services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"  
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      - MONGO_INITDB_DATABASE: ${DB_NAME}
    restart: always
    command: mongo --auth  
        

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
<<<<<<< HEAD
    driver: local 
=======
    driver: local  
>>>>>>> d5ea30f8c7a2bd028b56a1dd7e95408e553a5a28
