name: aws-destroy

on:
  workflow_dispatch:


jobs:
    destroy_bucket:
      name: destroy
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut
          uses: actions/checkout@v3
        - name: set up terraform hashicorp
          uses: hashicorp/setup-terraform@v1

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{env.us-east-1}}
           
  
        - name: terraform init
          run: |
            cd Task2
            terraform init 
            
        - name: destroy
          run: |
            cd Task2
            terraform destroy -auto-approve